<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="ServiceLib.Enums" />
    <Compile Include="../../upstream/v2rayN/v2rayN/Features/QuickSplit/QuickSplitLogic.cs" Link="QuickSplitLogic.cs" />
    <Compile Include="../../upstream/v2rayN/ServiceLib/Models/Entities/RulesItem.cs" Link="RulesItem.cs" />
    <Compile Include="../../upstream/v2rayN/ServiceLib/Enums/ERuleType.cs" Link="ERuleType.cs" />
  </ItemGroup>
</Project>
